config/routes.rb
Meublespecoste::Application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :users do
      as_routes
    end
    resources :pages do
      as_routes
    end
    resources :contents do
      as_routes
    end
    resources :categories do
      as_routes
    end
    resources :products do
      as_routes

    end
    resources :pictures do
      as_routes

    end
    resources :params do
      as_routes
    end
    resources :posts do
      as_routes
    end
    resources :stores do
      as_routes
    end
    root :to => 'categories#index'
  end

  resources :categories, :only => [:index, :show], :path => 'gammes' do
    resources :products, :only => [:show], :path => 'creation'
  end

  resources :posts, :only => [:index, :show], :path => 'evenements'

  match 'skills/' => 'skills#index', :path => 'notre-savoir-faire'

  resources :contacts, :only => [:index, :create], :path => 'contact'

  root :to => "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_friendly_id :name, :use_slug => true

  has_attached_file :image, :styles => { :admin => ['50x50!',:jpg], :default => ['127x293!',:jpg] }

  validates_attachment_presence :image
  validates_presence_of :name

  has_many :products

  default_scope :order => 'position ASC'
end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Naming
  include ActiveModel::Conversion

  validates_presence_of :name, :email, :subject, :message

  attr_accessor :name, :email, :subject, :message

  def initialize(attributes = {})
    attributes.each do |key, value|
      send("#{key}=",value)
    end
  end

  def persisted?
    false
  end


end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :page
  cache_constants :name

  def to_label
    label
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :contents

  cache_constants :name


end

app/models/param.rb
class Param < ActiveRecord::Base
  cache_constants :name

  serialize :value

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  has_attached_file :image, :styles => { :admin => ['50x50!',:jpg], :default => ['x260',:jpg] }

  belongs_to :product


  default_scope :order => 'position ASC'

  validates_attachment_presence :image

end

app/models/post.rb
class Post < ActiveRecord::Base

  cattr_reader :per_page
  @@per_page = 3

  def self.published
    where(:published_on ^ '0000-00-00')
  end

  default_scope :order => 'published_on desc'
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_friendly_id :name, :cache_column => 'cached_slug', :use_slug => true

  has_attached_file :image, :styles => { :admin => ['50x50!',:jpg], :default => ['x150',:jpg] }

  belongs_to :category

  has_many :pictures

  validates_attachment_presence :image
  validates_presence_of :name

  default_scope :order => 'position ASC'
end

app/models/store.rb
class Store < ActiveRecord::Base

  acts_as_gmappable

  default_scope :order => 'position ASC'

  after_validation {|store|
    if ( (store.changed.map(&:to_sym) & [:street, :zip_code, :city] ).size != 0 )
      store.gmaps = false
    end
  }


  def gmaps4rails_address
    [street, zip_code, city, 'FRANCE'].join(' ')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  #  , :trackable,


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController

  active_scaffold :categories do |config|
    config.columns = [:name, :image, :products]
    config.create.columns = config.update.columns = config.show.columns = [:name, :image]
    config.actions << :sortable
    config.sortable.column = :position
    config.columns[:slug].association.reverse = :product
    config.columns[:slugs].association.reverse = :product
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  layout :choose_layout

  def choose_layout
    if request.xhr?
      false
    elsif devise_controller?
      'authenticate'
    else
      'application'
    end
  end

  def get_categories
    @categories = Category.all
  end

  def get_category
    @category = Category.find_by_cached_slug(params[:category_id])
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :get_categories

  def index
    @posts = Post.published.limit(2)
    @stores = Store.all
  end

  def show
    @category = Category.find_by_cached_slug(params[:id])
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @stores = Store.all
    @json = @stores.to_gmaps4rails
    @contact = Contact.new()
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      flash.now[:notice]= "Votre message nous a été envoyé"
      ContactMailer.contact_message(@contact).deliver
      ContactMailer.feed_back_message(@contact).deliver if Param::SEND_FEEDBACK_EMAIL
      @contact = Contact.new
    else
      flash.now[:warning]= "Veuillez remplir les champs en rouge"
    end
    render :create
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.published.paginate(:page => params[:page], :per_page => Post.per_page)
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :get_categories, :get_category

  def show
    @product = Product.find_by_cached_slug(params[:id])
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index

  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper

  def image_column(record)
    image_tag(record.image.url(:admin))
  end

#  def products_column(record)
#    if record.products.blank?
#      raw link_to "Ajouter une création", url_for(:action => :new, :controller => :products, :category_id => record.id, :parent_scaffold => 'admin_categories', :eid => "admin__categories_#{record.id}_products"), :remote => true, :inline => true, :position => 'after',:type => 'member'
#    else
#      raw record.products.collect{|p| image_tag(p.image.url(:admin))}.join()
#    end
#  end
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper

  def title_column(record)
    raw record.title
  end
  def sub_title_column(record)
    raw record.sub_title
  end
  def title_show_column(record)
    title_column(record)
  end
  def sub_title_show_column(record)
    sub_title_column(record)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/categories/_category_wrapper.html.haml
#text
  %h1= raw Page::CATEGORIES.title
  %h2= raw Page::CATEGORIES.sub_title
  .content= raw Content::CATEGORIES_MAIN_TEXT.text

%ul#categories
  - @categories.each do |category|
    %li= link_to category.name, category_path(category, :anchor => 'text'), :class => ( category == @category ? 'selected' : '' )

= yield

#sur-mesure.bottom-titles
  %h1= raw Content::CATEGORIES_BOTTOM_TITLE.text
  %h2= raw Content::CATEGORIES_BOTTOM_TEXT.text

app/views/categories/index.html.haml
%ul#categories
  - @categories.each do |category|
    %li
      = link_to category_path(category) do
        = image_tag category.image.url(:default)
        %span= category.name

#text
  %h1= raw Page::HOME.title
  %h2= raw Page::HOME.sub_title

  .content
    = raw Content::HOME_MAIN_TEXT.text
    .bottom-link
      = link_to "VOIR TOUTES NOS RÉALISATIONS  >", category_path(Category.first)


#contact
  %h1= raw Content::HOME_CONTACT_TITLE.text
  .content
    %ul
      - @stores.each do |store|
        %li
          %div= store.street
          %div= [store.zip_code, store.city].join(' ').upcase
          .phone= "Tel. #{store.phone_number}"
          .fax= "Fax. #{store.fax_number}"

  .bottom-link
    = link_to  "Nous envoyer un mail >", contacts_path






#posts
  %h1= raw Content::HOME_EVENTS_TITLE.text
  %ul
    - @posts.each do |post|
      %li
        %h3
          %span.published_on= l(post.published_on)
          \-
          = raw post.title
        .content
          = truncate(raw(post.content), :length => 240)
          = link_to 'voir la suite', post_path(post)

app/views/categories/show.html.haml
= render :layout => 'categories/category_wrapper' do
  %ul#products
    - @category.products.each do |product|
      %li
        = link_to category_product_path(@category, product, :anchor => 'text') do
          = image_tag product.image.url(:default), :title => product.name