config/routes.rb
Meublespecoste::Application.routes.draw do

  devise_for :users

  namespace :admin do
    resources :users do
      as_routes
    end
    resources :pages do
      as_routes
    end
    resources :contents do
      as_routes
    end
    resources :categories do
      as_routes
    end
    resources :products do
      as_routes

    end
    resources :pictures do
      as_routes

    end
    resources :params do
      as_routes
    end
    resources :posts do
      as_routes
    end
    resources :stores do
      as_routes
    end
    root :to => 'categories#index'
  end

  resources :categories, :only => [:index, :show], :path => 'gammes' do
    resources :products, :only => [:show], :path => 'creation'
  end

  resources :posts, :only => [:index, :show], :path => 'evenements'

  match 'skills/' => 'skills#index', :path => 'notre-savoir-faire'

  resources :contacts, :only => [:index, :create], :path => 'contact'

  root :to => "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_friendly_id :name, :use_slug => true

  has_attached_file :image, :styles => { :admin => ['50x50!',:jpg], :default => ['127x293!',:jpg] }

  validates_attachment_presence :image
  validates_presence_of :name

  has_many :products

  default_scope :order => 'position ASC'
end

app/models/contact.rb
class Contact

  include ActiveModel::Validations
  include ActiveModel::Naming
  include ActiveModel::Conversion

  validates_presence_of :name, :email, :subject, :message

  attr_accessor :name, :email, :subject, :message

  def initialize(attributes = {})
    attributes.each do |key, value|
      send("#{key}=",value)
    end
  end

  def persisted?
    false
  end


end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :page
  cache_constants :name

  def to_label
    label
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  has_many :contents

  cache_constants :name


end

app/models/param.rb
class Param < ActiveRecord::Base
  cache_constants :name

  serialize :value

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  has_attached_file :image, :styles => { :admin => ['50x50!',:jpg], :default => ['x260',:jpg] }

  belongs_to :product


  default_scope :order => 'position ASC'

  validates_attachment_presence :image

end

app/models/post.rb
class Post < ActiveRecord::Base

  cattr_reader :per_page
  @@per_page = 3

  def self.published
    where(:published_on ^ '0000-00-00')
  end

  default_scope :order => 'published_on desc'
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_friendly_id :name, :cache_column => 'cached_slug', :use_slug => true

  has_attached_file :image, :styles => { :admin => ['50x50!',:jpg], :default => ['x150',:jpg] }

  belongs_to :category

  has_many :pictures

  validates_attachment_presence :image
  validates_presence_of :name

  default_scope :order => 'position ASC'
end

app/models/store.rb
class Store < ActiveRecord::Base

  acts_as_gmappable

  default_scope :order => 'position ASC'

  after_validation {|store|
    if ( (store.changed.map(&:to_sym) & [:street, :zip_code, :city] ).size != 0 )
      store.gmaps = false
    end
  }


  def gmaps4rails_address
    [street, zip_code, city, 'FRANCE'].join(' ')
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  #  , :trackable,


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @stores = Store.all
    @json = @stores.to_gmaps4rails
    @contact = Contact.new()
  end

  def create
    @contact = Contact.new(params[:contact])
    if @contact.valid?
      flash.now[:notice]= "Votre message nous a été envoyé"
      ContactMailer.contact_message(@contact).deliver
      ContactMailer.feed_back_message(@contact).deliver if Param::SEND_FEEDBACK_EMAIL
      @contact = Contact.new
    else
      flash.now[:warning]= "Veuillez remplir les champs en rouge"
    end
    render :create
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.published.paginate(:page => params[:page], :per_page => Post.per_page)
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :get_categories, :get_category

  def show
    @product = Product.find_by_cached_slug(params[:id])
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/admin.html.haml
%html
  %head
    = javascript_include_tag :admin
    = stylesheet_link_tag 'jquery-ui-humanity/jquery-ui-1.8.11.custom', 'compiled/admin'
    = active_scaffold_includes
    = csrf_meta_tag
  %body
    #page
      = link_to "Voir le site", root_path, :target => "_blank", :id => "popup-website", :class =>"ui-widget-content ui-state-highlight ui-corner-top"
      #header.ui-widget.ui-widget-header.ui-corner-bottom
        %h1 ADMIN::MEUBLES-PECOSTE.FR
      #devise
        #devise-options
          Bonjour
          = "#{current_user.email},"
          = link_to "déconnection", destroy_user_session_path
        .notice= notice
        .alert= alert
      #tabs
        %ul
          %li= link_to "Gammes", "#admin-categories"
          %li= link_to "Pages & contenus", admin_pages_path
          %li= link_to "Evenements", admin_posts_path
          %li= link_to "Magasins", admin_stores_path
          %li= link_to "Administrateurs", admin_users_path
          %li= link_to "Paramètres", admin_params_path
        #admin-categories
          = yield

app/views/layouts/application.html.haml
%html
  %head
    = javascript_include_tag :defaults, "galleria/src/galleria", "galleria-theme-meublespecoste/galleria.meublespecoste"
    = stylesheet_link_tag 'compiled/application.css', :media => 'screen, projection'
    /[if IE]
      = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'
    %meta(name="description" content="Artisans-fabricants de cuisines et meubles. Depuis 1959, les établissements Pecoste fabriquent sur-mesure cuisine salle de bains et meuble en bois massif ")/
    %meta(name="keywords" content="meuble cuisine moderne tradition lit placards salle de bains dressing")/
    %meta(name="robots" content="index,follow")/

    %meta(name="viewport" content="width=1040;")

    -#%link(rel="apple-touch-icon" href="/images/iphone.png")
    -#%link(media="only screen and (max-device-width: 480px)" href="/stylesheets/compiled/iphone.css" type= "text/css" rel="stylesheet")

    = csrf_meta_tag

    = yield :head

  %body
    -#- if user_signed_in?
    -#  = link_to "Voir l'admin", admin_root_path, :id => "admin-link", :class =>"ui-widget-content ui-state-highlight ui-corner-all"
    #page-wrapper
      #page{:class => "#{params[:action].downcase}_#{params[:controller].downcase} #{params[:controller].downcase}" }
        #header
          %ul.menu
            %li= link_to Page::HOME.link, root_path, :class => request.path == root_path ? 'selected' : ''
            %li= link_to Page::CATEGORIES.link , category_path(Category.first), :class => (['categories', 'products'].include?(params[:controller])  and request.path != root_path )? 'selected' : ''
            %li= link_to Page::SKILLS.link, skills_path, :class => request.path == skills_path ? 'selected' : ''
            %li= link_to Page::POSTS.link, posts_path, :class => params[:controller] == 'posts' ? 'selected' : ''
            %li.last= link_to Page::CONTACT.link, contacts_path, :class => request.path == contacts_path ? 'selected' : ''
          .spacer
        #content
          = yield
        #bottom
          .menu
            = link_to link_to Page::HOME.link, root_path
            %span /
            = link_to Page::CATEGORIES.link , category_path(Category.first)
            %span /
            = link_to Page::SKILLS.link, skills_path
            %span /
            = link_to Page::POSTS.link, posts_path
            %span /
            = link_to Page::CONTACT.link, contacts_path

    = yield :scripts

app/views/layouts/authenticate.html.haml
%html
  = stylesheet_link_tag 'jquery-ui-humanity/jquery-ui-1.8.11.custom', 'compiled/authenticate'
  = csrf_meta_tag
  %title ADMIN
%body
  #page
    #flash
      - unless notice.blank?
        .notice= notice
      - unless alert.blank?
        .error= alert
    #auth-box.ui-widget.ui-widget-content.ui-corner-all
      = yield